In [5]:
# 참고: https://hunkim.github.io/ml/
#       https://gist.github.com/j-min/481749dcb853b4477c4f441bf7452195

import tensorflow as tf
import numpy as np 

In [7]:
char_rdic = ['h', 'e', 'l', 'o']  # id -> char
char_dic = {w: i for i, w in enumerate(char_rdic)} # char -> id
print(char_dic)

{'h': 0, 'e': 1, 'l': 2, 'o': 3}


In [8]:
ground_truth = [char_dic[c] for c in 'hello']
print(ground_truth)

[0, 1, 2, 2, 3]


In [17]:
# Input layer
x_data = np.array([[1, 0, 0, 0],  # h
                  [0, 1, 0, 0],   # e
                  [0, 0, 1, 0],   # l
                  [0, 0, 1, 0]],  # l
                 dtype='f')

#x_data = tf.one_hot(ground_truth[:-1], len(char_dic), 1.0, 0.0, -1)
#print(x_data)

In [38]:
tf.reset_default_graph()

# Configuration
char_vocab_size = len(char_dic)
rnn_size = char_vocab_size        #  hot coding (one of 4)
time_step_size = 4                #' hell' -> predict 'ello'
batch_size = 1                    # one sample

# RNN model
rnn_cell = tf.nn.rnn_cell.BasicRNNCell(num_units=rnn_size)
state = tf.zeros([batch_size, rnn_cell.state_size])
X_split = tf.split(x_data, time_step_size, 0)
outputs, state = tf.contrib.rnn.static_rnn(rnn_cell, X_split, state)

# logits: list of 2D Tensors of shape [batch_size x num_decoder_sysbols]
# targets: list of 1D batch-sized int32 Tensors of the same length as logits.
# weights: list of 1D batch-sized float-Tensors of the same length as logits.
logits = tf.reshape(tf.concat(outputs, 1), [-1, rnn_size]) 
targets = tf.reshape(ground_truth[1:], [-1])                     
weights = tf.ones([time_step_size * batch_size])  

In [43]:
# Cost
loss = tf.contrib.legacy_seq2seq.sequence_loss_by_example([logits], [targets], [weights])
cost = tf.reduce_sum(loss) / batch_size
train_op = tf.train.RMSPropOptimizer(0.01, 0.9).minimize(cost)

# Train & Prediction
# Launch the graph in a session
with tf.Session() as sess:
    # you need to initialize all variables
    tf.initialize_all_variables().run()
    
    for i in range(100):
        sess.run(train_op)
        result = sess.run(tf.arg_max(logits, 1))
        print(result, [char_rdic[t] for t in result])

[2 0 0 1] ['l', 'h', 'h', 'e']
[2 0 0 1] ['l', 'h', 'h', 'e']
[2 0 0 1] ['l', 'h', 'h', 'e']
[2 0 0 1] ['l', 'h', 'h', 'e']
[2 0 0 1] ['l', 'h', 'h', 'e']
[2 0 0 1] ['l', 'h', 'h', 'e']
[2 0 0 1] ['l', 'h', 'h', 'e']
[2 0 0 1] ['l', 'h', 'h', 'e']
[2 0 0 1] ['l', 'h', 'h', 'e']
[2 0 0 3] ['l', 'h', 'h', 'o']
[2 0 0 3] ['l', 'h', 'h', 'o']
[2 0 0 3] ['l', 'h', 'h', 'o']
[2 0 3 3] ['l', 'h', 'o', 'o']
[2 0 3 3] ['l', 'h', 'o', 'o']
[2 0 3 3] ['l', 'h', 'o', 'o']
[2 1 3 3] ['l', 'e', 'o', 'o']
[2 1 3 3] ['l', 'e', 'o', 'o']
[2 1 3 3] ['l', 'e', 'o', 'o']
[2 1 3 3] ['l', 'e', 'o', 'o']
[2 1 3 3] ['l', 'e', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 3 3] ['l', 'l', 'o', 'o']
[2 2 2 3] ['l', 'l', 'l', 'o']
[2 2 2 3